package org.example.minispringap12.dto;

import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Size;

public record UserDTO(
        @NotEmpty(message = "Username cannot be empty")
        @Size(min = 3, max = 15, message = "Username must be between 3 and 15 characters")
        String username,

        @NotEmpty(message = "Password cannot be empty")
        @Size(min = 5, message = "Password must be at least 5 characters long")
        String password
) {
    // No need for custom constructor and getters in a record class as they are generated by default
}
